#!/usr/bin/env python3
import os, sys

_srcdir = '%s/' % os.path.dirname(os.path.realpath(__file__))
_filepath = os.path.dirname(sys.argv[0])
sys.path.insert(1, os.path.join(_filepath, _srcdir))

if sys.version_info[0] == 3:
    from pycrawler import Core
    if __name__ == '__main__':
        core = Core()
        try:
            core.start()
        except KeyboardInterrupt:
            core.log.info(core._("Killed from terminal"))
            core.terminate()
            os._exit(1)
else: # Python 2
    from pycrawler.sources.logger import getLogger
    log = getLogger()
    log.e("[fatal] Python 3 is required!")
    log.wtf("try to run this script using 'python3 start'.")
